GCC detection.

diff --git a/bin/mono-build b/bin/mono-build
--- a/bin/mono-build
+++ b/bin/mono-build
@@ -162,6 +162,79 @@ build_package_mono_source() {
 	} >&4 2>&1
 }
 
+require_gcc() {
+	local gcc="$(locate_gcc || true)"
+	if [ -z "$gcc" ]; then
+		{ 
+			echo
+			echo "ERROR: This package must be compiled with GCC, and we"
+			echo "couldn't find a suitable \`gcc' binary on your system."
+			echo "Please install GCC and try again."
+			echo
+
+			if [ "$(uname -s)" = "Darwin" ]; then
+				echo "As of version 4.2, Xcode is LLVM-only and no longer"
+				echo "includes GCC. You can install GCC with these binary"
+				echo "packages on Mac OS X:"
+				echo
+				echo "https://github.com/kennethreitz/osx-gcc-installer/downloads"
+				echo
+			fi
+		} >&3
+		return 1
+  	fi
+
+  	export CC="$gcc"
+}
+
+locate_gcc() {
+	local gcc gccs
+	IFS=: gccs=($(gccs_in_path))
+
+	verify_gcc "$CC" ||
+	verify_gcc "$(command -v gcc || true)" || {
+		for gcc in "${gccs[@]}"; do
+			verify_gcc "$gcc" && break || true
+		done
+	}
+
+	return 1
+}
+
+gccs_in_path() {
+	local gcc path paths
+	local gccs=()
+	IFS=: paths=($PATH)
+
+	shopt -s nullglob
+	for path in "${paths[@]}"; do
+		for gcc in "$path"/gcc-*; do
+			gccs["${#gccs[@]}"]="$gcc"
+		done
+	done
+	shopt -u nullglob
+
+	printf :%s "${gccs[@]}"
+}
+
+verify_gcc() {
+	local gcc="$1"
+	if [ -z "$gcc" ]; then
+		return 1
+	fi
+
+	local version="$("$gcc" --version || true)"
+	if [ -z "$version" ]; then
+		return 1
+	fi
+
+	if echo "$version" | grep LLVM >/dev/null; then
+		return 1
+	fi
+
+	echo "$gcc"
+}
+
 version() {
 	echo "mono-build ${MONO_BUILD_VERSION}"
 }
