Trapping errors and adding verbose support.
    * Use file descriptors to avoid swallowing errors.
    * Print error message on error.

diff --git a/bin/mono-build b/bin/mono-build
--- a/bin/mono-build
+++ b/bin/mono-build
@@ -3,6 +3,7 @@
 MONO_BUILD_VERSION="0.1.0"
 
 set -E
+exec 3<&2 # preserve original stderr at fd 3
 
 abs_dirname() {
 	local cwd="$(pwd)"
@@ -16,6 +17,38 @@ abs_dirname() {
 
 	pwd
 	cd "$cwd"
+}
+
+build_failed() {
+	{
+		echo
+		echo "BUILD FAILED"
+		echo
+
+		if ! rmdir "${TEMP_PATH}" 2>/dev/null; then
+			echo "Inspect or clean up the working tree at ${TEMP_PATH}"
+
+			if file_is_not_empty "$LOG_PATH"; then
+				echo "Results logged to ${LOG_PATH}"
+				echo
+				echo "Last 20 log lines:"
+				tail -n 20 "$LOG_PATH"
+			fi
+		fi
+	} >&3
+	exit 1
+}
+
+file_is_not_empty() {
+	local filename="$1"
+	local line_count="$(wc -l "$filename" 2>/dev/null || true)"
+
+	if [ -n "$line_count" ]; then
+		words=( $line_count )
+		[ "${words[0]}" -gt 0 ]
+	else
+		return 1
+	fi
 }
 
 install_package() {
@@ -41,7 +74,7 @@ download_package() {
 	echo "Downloading ${package_url}..." >&2
 
 	{ curl "$package_url" > "${package_name}.tar.bz2"
-	} >$LOG_PATH 2>&1
+	} >&4 2>&1
 }
 
 extract_package() {
@@ -50,7 +83,7 @@ extract_package() {
 	echo "Extracting ${package_name}..." >&2
 
 	{ tar xjvf "${package_name}.tar.bz2"
-	} >$LOG_PATH 2>&1
+	} >&4 2>&1
 }
 
 build_package() {
@@ -76,7 +109,7 @@ build_package_standard() {
 	{ ./configure --prefix="$PREFIX_PATH"
 	  make
 	  make install
-	} >$LOG_PATH 2>&1
+	} >&4 2>&1
 }
 
 build_package_mono() {
@@ -89,7 +122,7 @@ build_package_mono() {
 	{ ./configure --prefix="$PREFIX_PATH" $options
 	  make
 	  make install
-	} >$LOG_PATH 2>&1
+	} >&4 2>&1
 }
 
 version() {
@@ -98,7 +131,7 @@ version() {
 
 usage() {
 	version
-	{ echo "usage: mono-build definition prefix"
+	{ echo "usage: mono-build [-v|--verbose] definition prefix"
 	  echo "       mono-build --definitions"
 	} >&2
 	if [ -z "$1" ]; then
@@ -113,6 +146,7 @@ list_definitions() {
 	} | sort
 }
 
+unset VERBOSE
 MONO_BUILD_ROOT="$(abs_dirname "$0")/.."
 
 case "$1" in
@@ -121,6 +155,7 @@ case "$1" in
 	{ echo
 	  echo "Options:"
 	  echo
+	  echo "  -v/--verbose     Verbose mode: print compilation status to stdout"
 	  echo "  --definitions    List all built-in definitions"
 	} >&2
 	exit 0
@@ -132,6 +167,10 @@ case "$1" in
 "--definitions" )
 	list_definitions
 	exit 0
+	;;
+"-v" | "--verbose" )
+	VERBOSE=true
+	shift
 	;;
 esac
 
@@ -158,9 +197,17 @@ LOG_PATH="/tmp/mono-build.${SEED}.log"
 TEMP_PATH="/tmp/mono-build.${SEED}"
 CWD="$(pwd)"
 
+exec 4<> "$LOG_PATH" # open the log file at fd 4
+if [ -n "$VERBOSE" ]; then
+	tail -f "$LOG_PATH" &
+	trap "kill 0" SIGINT SIGTERM EXIT
+fi
+
 export LDFLAGS="-L'${PREFIX_PATH}/lib' ${LDFLAGS}"
 export CPPFLAGS="-I'${PREFIX_PATH}/include' ${CPPFLAGS}"
 
+trap build_failed ERR
 mkdir -p "$TEMP_PATH"
 source "$DEFINITION_PATH"
 rm -fr "$TEMP_PATH"
+trap - ERR
